version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - "15432:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: alexsantini90@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass123